USE [master]
GO

/****** Object:  Database [Challenge]    Script Date: 1/22/2019 5:32:31 PM ******/
CREATE DATABASE [Challenge]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Challenge', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Challenge.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Challenge_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Challenge_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Challenge] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Challenge].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Challenge] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Challenge] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Challenge] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Challenge] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Challenge] SET ARITHABORT OFF 
GO

ALTER DATABASE [Challenge] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Challenge] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Challenge] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Challenge] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Challenge] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Challenge] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Challenge] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Challenge] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Challenge] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Challenge] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Challenge] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Challenge] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Challenge] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Challenge] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Challenge] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Challenge] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Challenge] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Challenge] SET RECOVERY FULL 
GO

ALTER DATABASE [Challenge] SET  MULTI_USER 
GO

ALTER DATABASE [Challenge] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Challenge] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Challenge] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Challenge] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Challenge] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Challenge] SET QUERY_STORE = OFF
GO

USE [Challenge]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Challenge] SET  READ_WRITE 
GO


